### ISSUE TITLE
Feature request: Also Group initiatives when the Roll All button is used

### ISSUE THREAD

**Issue by Norc** [tonifisler/foundry-group-initiative#1]
I'd love to use the "Roll All" button in the combat tracker, but Group Initiative requires me to use the Roll NPCs button instead. 

It is only a few clicks to manually roll each of my party members, but it gets annoying. Also, the current set up is a bit counter-intuitive. It was confusing to me why it "wasn't working" at first when I initially installed it alongside 700 other modes while getting set up with Foundry and was clicking "Roll All."

**Comment by tonifisler** [comment]
You're right, it should roll with all buttons and/or say how it works in a simple manner. I'll add a better help text too.
