### ISSUE TITLE
compatibility with v0.8.5

### ISSUE THREAD

**Issue by davidR1974** [tonifisler/foundry-group-initiative#9]
Hello,

when reviewing module compatility with 0.8.5 and was able to make Group Initiative work (or i think so)  by modifying line 136-138 of group-initiative.js by replacing 

`Hooks.on('renderCombatTracker', ( {combat} ) => {`

with 

```
Hooks.on('renderCombatTracker', ( app, html, options ) => {

  let combat = options.combat ;
```

don't know if that is helpful for you.

Regards,
David

**Comment by bekriebel** [comment]
@tonifisler This fix does indeed work, but hasn't been released yet. With the release of FVTT 0.8.6 today, can you cut a new release and update the module.json so it can be easily installed?

Thanks!
